Program Quiz_API ;
Var
	r:char;
	x,op,i,k,f:shortint;
	nome:array[1..14] of string;
	pontos:array[1..14] of shortint;
	limiteperguntas:array[1..14] of shortint;
Begin
for i:=25 to 65 do
  					begin
				    textcolor(cyan);
				    gotoxy(i,4);
				    write(#205);
				    gotoxy(i,11);
				    write(#205);
				  end;
				  for i:=5 to 10 do
				  	begin
					    textcolor(cyan);
					    gotoxy(25,i);
					    write(#186);
					    gotoxy(65,i);
					    write(#186);
				  	end;
				  gotoxy(25,11);
				  write(#200);
				  gotoxy(65,4);
				  write(#187);
				  gotoxy(25,4);
				  write(#201);
				  gotoxy(65,11);
				  write(#188);
				  gotoxy(36,6);
				  textcolor(lightcyan);
				  write('Escreva o seu nome');
				  gotoxy(41,8);
				  textcolor(white);
				  k:=1;
					read(nome[k]);
					limiteperguntas[k]:=0;
					gotoxy(51,8);
					delay(100);
				  clrscr;
  Repeat
    Textcolor(brown);
    For i:=35 to 60 do
    begin
      gotoxy(i,2);
      write(#205);
      gotoxy(i,18);
      write(#205);
    end;    
    For i:=3 to 17 do
    begin
      gotoxy(34,i);
      write(#186);
      gotoxy(61,i);
      write(#186);
    end;    
    gotoxy(34,2);
    write(#201);
    gotoxy(61,2);
    write(#187);
    gotoxy(34,18);
    write(#200);
    gotoxy(61,18);
    write(#188);   
    Gotoxy(43,4);
    textcolor(yellow);
    write('TRIVIALZIM');
    Gotoxy(37,7);
    textcolor(lightcyan);
    write('1-JOGAR') ;
    Gotoxy(37,9);
    textcolor(lightblue);
    write('2-INSERIR OUTRO JOGADOR') ;   
    Gotoxy(37,11);
    textcolor(magenta);
    write('3-LEADERBOARD') ;
    Gotoxy(37,13);
    textcolor(green);
    write('4-SAIR');
    Gotoxy(37,15);
    textcolor(red);
    write('Digite Opção: ') ;
    read(op);
    clrscr;
    case op of
      2:Begin
          for i:=25 to 65 do
  					begin
				    textcolor(cyan);
				    gotoxy(i,4);
				    write(#205);
				    gotoxy(i,11);
				    write(#205);
				  end;
				  for i:=5 to 10 do
				  	begin
					    textcolor(cyan);
					    gotoxy(25,i);
					    write(#186);
					    gotoxy(65,i);
					    write(#186);
				  	end;
				  gotoxy(25,11);
				  write(#200);
				  gotoxy(65,4);
				  write(#187);
				  gotoxy(25,4);
				  write(#201);
				  gotoxy(65,11);
				  write(#188);
				  gotoxy(36,6);
				  textcolor(lightcyan);
				  write('Escreva o seu nome');
				  gotoxy(41,8);
				  textcolor(white);
				  k:=k+1;
					read(nome[k]);
					limiteperguntas[k]:=0;
					gotoxy(51,8);
					delay(100);
				  clrscr;
        end;
      1:Begin
        	randomize;
        	f:=0;
        	Repeat
        	  for i:=20 to 65 do
						   begin
						 		textcolor(lightblue);
							 	gotoxy(i,3);
							 	write(#205);
							 	gotoxy(i,8);
							 	write(#205);
							 end;						
						 for i:=4 to 7 do
						 	begin
							  textcolor(lightblue);
								gotoxy(19,i);
								write(#186);
								gotoxy(66,i);
								write(#186);
							end;							
						 gotoxy(19,3);
						 write(#201);
						 gotoxy(66,3);
						 write(#187);
						 gotoxy(19,8);
						 write(#200);
						 gotoxy(66,8);
						 write(#188);						  
						 for i:=20 to 65 do
						   begin
						 		textcolor(lightblue);
							 	gotoxy(i,9);
							 	write(#205);
							 	gotoxy(i,15);
							 	write(#205);
							 end;						
						 for i:=10 to 14 do
						 	 begin
							  textcolor(lightblue);
								gotoxy(19,i);
								write(#186);
								gotoxy(66,i);
								write(#186);
							 end;							
						 gotoxy(19,9);
						 write(#201);
						 gotoxy(66,9);
						 write(#187);
						 gotoxy(19,15);
						 write(#200);
						 gotoxy(66,15);
						 write(#188);						 
						 for i:=10 to 14 do
						 	begin
						 		textcolor(lightblue);
						 		gotoxy(42,i);
						 		write(#186);
						  end;						  
						 gotoxy(42,9);
						 write(#203);
						 gotoxy(42,15);
						 write(#202);						 
						 for i:=20 to 65 do
						 	begin
						 		textcolor(lightblue);
						 		gotoxy(i,12);
						 		write(#205);
						 	end;						 	
						 gotoxy(19,12);
						 write(#204);
						 gotoxy(66,12);
						 write(#185);
						 gotoxy(42,12);
						 write(#206);
						 for i:=40 to 44 do
						 	begin
							 	textcolor(lightblue);
							 	gotoxy(i,16);
							 	write(#205);
							 	gotoxy(i,18);
							 	write(#205);
						 	end;						 	
						 gotoxy(39,17);
						 write(#186);
						 gotoxy(45,17);
						 write(#186);
						 gotoxy(39,16);
						 write(#201);
						 gotoxy(45,16);
						 write(#187);
						 gotoxy(39,18);
						 write(#200);
						 gotoxy(45,18);
						 write(#188);
						gotoxy(40,17);
						textcolor(white);
						write('R:');
        	x:=random(50)+1;
	        	case x of 
	        		1:Begin
	        		    gotoxy(21,4);
	        				textbackground(green);
									write('"Infelizmente');
									gotoxy(34,4);
									textbackground(black);
									writeln(', uma página da enciclopédia');
									gotoxy(35,5);
									write('foi arrancada."');
									gotoxy(21,6);
									writeln('Qual é a função da expressão sublinhada?');
									gotoxy(20,10);
									writeln('A- SUJEITO');
									gotoxy(43,10);
									writeln('B- VOCATIVO');
									gotoxy(20,13);
									writeln('C- PREDICATIVO DO');
									gotoxy(26,14);
									write('SUJEITO');
									gotoxy(43,13);
									writeln('D- MODIFICADOR DE FRASE');
									gotoxy(42,17);
									readln(r);
									if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
									delay(1000);
								end;
							2:Begin                                                 
									gotoxy(24,5);
									writeln('Qual destas opções não é um processo');
									gotoxy(35,6);     
									write('de fossilização?');
									gotoxy(20,10);
									writeln('A- MINERALIZAÇÃO');
									gotoxy(44,10);
									writeln('B- COMPACTAÇÃO');
									gotoxy(20,13);
									writeln('C- MOLDAGEM');
									gotoxy(44,13);
									writeln('D- CONSERVAÇÃO');
									gotoxy(42,17);
									readln(r);
									if (r = 'B') or (r= 'b') then pontos[k]:=pontos[k]+1;
									delay(1000);						          
								end;	
					    3:Begin
									gotoxy(23,5);
									writeln('Em que ano se deu a batalha de S. Mamede?');
									gotoxy(21,10);
									writeln('A- 1128');
									gotoxy(44,10);
									writeln('B- 1130');
									gotoxy(21,13);
									writeln('C- 1125');
									gotoxy(44,13);
									writeln('D- 1139');
									gotoxy(42,17);
									readln(r);
									if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
									delay(1000);
								end;
							4:Begin
	                gotoxy(25,5);
									writeln('Qual destas misturas não é uma mistura');
									gotoxy(38,6);
									write('homogénea?');
									gotoxy(21,10);
									writeln('A- ÁGUA COM AÇÚCAR');
									gotoxy(44,10);
									writeln('B- AR');
									gotoxy(21,13);
									writeln('C- ÁGUA COM ÓLEO');
									gotoxy(44,13);
									writeln('D- ÁGUA COM CLORETO');
									gotoxy(51,14);
									write('DE SÓDIO');
									gotoxy(42,17);
									readln(r);
									if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
									delay(1000);
								end;
							5:Begin
	                gotoxy(21,5);
									writeln('Em qual destas etapas de formação de rochas');
									gotoxy(27,6);
									write('sedimentares dá-se a cimentação?');
									gotoxy(21,10);
									writeln('A- EROSÃO');
									gotoxy(44,10);
									writeln('B- DIAGÉNESE');
									gotoxy(21,13);
									writeln('C- METEORIZAÇÃO');
									gotoxy(44,13);
									writeln('D- TRANSPORTE');
									gotoxy(42,17);
									readln(r);
									if (r = 'B') or (r	= 'b') then pontos[k]:=pontos[k]+1;
									delay(1000);
								end;
							6:Begin
	                gotoxy(24,5);
									writeln('Qual das seguintes letras representa o');
									gotoxy(27,6);
									write('conjunto dos números inteiros?');
									gotoxy(21,10);
									writeln('A- Z');
									gotoxy(44,10);
									writeln('B- Q');
									gotoxy(21,13);
									writeln('C- N');
									gotoxy(44,13);
									writeln('D- R');
									gotoxy(42,17);
									readln(r);
									if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
									delay(1000);
								end;
							 7:Begin
		               gotoxy(28,5);
									 writeln('Qual é a raiz quadrada de 81?');
									 gotoxy(21,10);
									 writeln('A- 7');
									 gotoxy(44,10);
									 writeln('B- 6');
									 gotoxy(21,13);
									 writeln('C- 9');
									 gotoxy(44,13);
									 writeln('D- 8');
									 gotoxy(42,17);
									 readln(r);
									 if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
									 delay(1000);
								 end;
								8:Begin
		                gotoxy(21,5);
										writeln('Em que reinado se deu a conquista definitiva');
										gotoxy(36,6);
										write('do Algarve?');
									  gotoxy(21,10);
										writeln('A- D. SANCHO I');
										gotoxy(44,10);
										writeln('B- D. SANCHO II');
										gotoxy(21,13);
										writeln('C- D. FERNANDO');
										gotoxy(44,13);
										writeln('D- D. AFONSO III');
										gotoxy(42,17);
										readln(r);
										if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
										delay(1000);
								  end;
								9:Begin
		                gotoxy(27,5);
										writeln('Qual das palavras que se seguem');
										gotoxy(33,6);
										write('é uma preposição?');
										gotoxy(21,10);
										writeln('A- DE');
										gotoxy(44,10);
										writeln('B- QUANDO');
										gotoxy(21,13);
										writeln('C- ONTEM');
										gotoxy(44,13);
										writeln('D- DEPOIS');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
								  end;
								10:Begin
			              gotoxy(27,5);
										writeln('Ao pôr-do-sol, o sol indica o ...');
										gotoxy(21,10);
										writeln('A- SUL');
										gotoxy(44,10);
										writeln('B- ESTE');
										gotoxy(21,13);
										writeln('C- OESTE');
										gotoxy(44,13);
										writeln('D- NORTE');
										gotoxy(42,17);
										readln(r);
										if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								11:Begin
		                gotoxy(23,5);
										writeln('Que nome se dá à mudança de estado físico');
										gotoxy(33,6);
										write('sólido para líquido?');
										gotoxy(21,10);
										writeln('A- CONDENSAÇÃO');
										gotoxy(44,10);
										writeln('B- VAPORIZAÇÃO');
										gotoxy(21,13);
										writeln('C- FUSÃO');
										gotoxy(44,13);
										writeln('D- SOLIDIFICAÇÃO');
										gotoxy(42,17);
										readln(r);
										if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								12:Begin
		                gotoxy(22,5);
										writeln('Qual destas alternativas apresenta apenas');
										gotoxy(34,6);
										write('dias da semana?');
										gotoxy(21,10);
										writeln('A- TUESDAY, THURSDAY,');
										gotoxy(24,11);
										write('HOLIDAY');
										gotoxy(44,10);
										writeln('B- MONDAY, FRIDAY,');
										gotoxy(47,11);
										write('SATURDAY');
										gotoxy(21,13);
										writeln('C- WEDNESDAY, SUNDAY,');
										gotoxy(24,14);
										write('MAY');
										gotoxy(44,13);
										writeln('D- FRIDAY, MAYDAY,');
										gotoxy(47,14);
										write('SUNDAY');
										gotoxy(42,17);
										readln(r);
										if (r = 'B') or (r= 'b') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								13:Begin
		                gotoxy(27,5);
										writeln('Em que tempo verbal está a frase');
										gotoxy(28,6);
										write('"She was cooking all morning"?');
										gotoxy(21,10);
										writeln('A- PAST CONTINUOUS');
										gotoxy(44,10);
										writeln('B- PRESENT CONTINUOUS');
										gotoxy(21,13);
										writeln('C- PAST SIMPLE');
										gotoxy(44,13);
										writeln('D- FUTURE');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								14:Begin
		                gotoxy(23,5);
										writeln('O Henrique tinha 100 euros e gastou 27%.');
										gotoxy(26,6);
										write('Com quantos euros o Henrique ficou?');
										gotoxy(21,10);
										writeln('A- 27');
										gotoxy(44,10);
										writeln('B- 73');
										gotoxy(21,13);
										writeln('C- 83');
										gotoxy(44,13);
										writeln('D- 37');
										gotoxy(42,17);
										readln(r);
										if (r = 'B') or (r= 'b') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								15:Begin
		                gotoxy(25,5);
										writeln('Na mitologia grega, quem é o deus');
										gotoxy(28,6);
										write('de todos os deuses ?');
										gotoxy(21,10);
										writeln('A- HERMES');
										gotoxy(44,10);
										writeln('B- HÉRCULES');
										gotoxy(21,13);
										writeln('C- ODIN');
										gotoxy(44,13);
										writeln('D- ZEUS');
										gotoxy(42,17);
										readln(r);
										if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								16:Begin
		                gotoxy(22,5);
										writeln('Qual é o maior planeta do sistema solar?');
										gotoxy(21,10);
										writeln('A- URANO');
										gotoxy(44,10);
										writeln('B- TERRA');                                                                                                                             
										gotoxy(21,13);
										writeln('C- JÚPITER');
										gotoxy(44,13);
										writeln('D- SATURNO');                                                                                      
										gotoxy(42,17);                                                                       
										readln(r);
										if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								17:Begin                                                                                                        
		                gotoxy(24,5);
										writeln('Em que ano aconteceu o 25 de Abril?');
										gotoxy(21,10);
										writeln('A- 1975');
										gotoxy(44,10);
										writeln('B- 1974');
										gotoxy(21,13);                                                                                                                   
										writeln('C- 1984');
										gotoxy(44,13);
										writeln('D- 1978');
										gotoxy(42,17);
										readln(r);                                                                                                   
										if (r = 'B') or (r= 'b') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
							  18:Begin                                                                                                                                                     
		                gotoxy(24,5);
										writeln('Qual é, em média, o tamanho do pénis');
										gotoxy(31,6);
										write('dum elefante adulto?');
										gotoxy(21,10);
										writeln('A- 1,8 metros');
										gotoxy(44,10);
										writeln('B- 2 metros');
										gotoxy(21,13);
										writeln('C- 1 metro');
										gotoxy(44,13);
										writeln('D- 1,3 metros');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								19:Begin
		                gotoxy(22,5);
										writeln('Em que ano começou a Revolução Francesa?');
										gotoxy(21,10);
										writeln('A- 1879');
										gotoxy(44,10);
										writeln('B- 1798');
										gotoxy(21,13);
										writeln('C- 1791');
										gotoxy(44,13);
										writeln('D- 1789');
										gotoxy(42,17);
										readln(r);
										if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								20:Begin
		                gotoxy(25,5);
										writeln('Em que península se situa Portugal?');
										gotoxy(21,10);
										writeln('A- ITÁLICA');
										gotoxy(44,10);
										writeln('B- PORTUGUESA');
										gotoxy(21,13);
										writeln('C- IBÉRICA');
										gotoxy(44,13);
										writeln('D- ESCANDINAVA');
										gotoxy(42,17);
										readln(r);
										if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								21:Begin
		                gotoxy(28,5);
										writeln('Quem ganhou o Euro 2004?');
										gotoxy(21,10);
										writeln('A- GRÉCIA');
										gotoxy(44,10);
										writeln('B- PORTUGAL');
										gotoxy(21,13);
										writeln('C- INGLATERRA');
										gotoxy(44,13);
										writeln('D- ESPANHA');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								22:Begin
		                gotoxy(24,5);
										writeln('Quem foi o último português a ganhar um');
										gotoxy(34,6);
										write('prémio Nobel?');
										gotoxy(21,10);
										writeln('A- CRISTIANO RONALDO');
										gotoxy(44,10);
										writeln('B- FERNANDO PESSOA');
										gotoxy(21,13);
										writeln('C- EGAS MONIZ');
										gotoxy(44,13);
										writeln('D- JOSÉ SARAMAGO');
										gotoxy(42,17);
										readln(r);
										if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								23:Begin
		                gotoxy(23,5);
										writeln('Quantos estados fazem parte dos EUA?');
										gotoxy(21,10);
										writeln('A- 25');
										gotoxy(44,10);           
										writeln('B- 50');
										gotoxy(21,13);
										writeln('C- 51');
										gotoxy(44,13);
										writeln('D- 47');
										gotoxy(42,17);
										readln(r);
										if (r = 'B') or (r= 'b') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								24:Begin
		                gotoxy(30,5);
										writeln('Qual é a capital dos EUA?');
										gotoxy(21,10);
										writeln('A- WASHINGTON DC');
										gotoxy(44,10);
										writeln('B- NOVA YORK');
										gotoxy(21,13);
										writeln('C- CALIFÓRNIA');
										gotoxy(44,13);
										writeln('D- FLÓRIDA');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								25:Begin
		                gotoxy(20,5);
										writeln('Quem é o atual primeiro-ministro de Portugal?');
										gotoxy(21,10);
										writeln('A- BORIS JOHNSON');
										gotoxy(44,10);
										writeln('B- CAVACO SILVA');
										gotoxy(21,13);
										writeln('C- MARCELO REBELO DE ');
										gotoxy(21,14);
										write('SOUSA');
										gotoxy(44,13);
										writeln('D- ANTÓNIO COSTA');
										gotoxy(42,17);
										readln(r);
										if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								26:Begin
		                gotoxy(22,5);
										writeln('Quem foi o primeiro rei de Portugal?');
										gotoxy(21,10);
										writeln('A- D.HENRIQUE');
										gotoxy(44,10);
										writeln('B- INFANTE D.HENRIQUE');
										gotoxy(21,13);
										writeln('C- D.AFONSO HENRIQUES');
										gotoxy(44,13);
										writeln('D- HENRIQUE VAZ CASTRO');
										gotoxy(42,17);
										readln(r);
										if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								27:Begin
		                gotoxy(22,5);
										writeln('Qual é a camada mais superficial da pele?');
										gotoxy(21,10);
										writeln('A- EPIDERME');
										gotoxy(44,10);
										writeln('B- DERME');
										gotoxy(21,13);
										writeln('C- HIPODERME');
										gotoxy(44,13);
										writeln('D- GENODERME');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								28:Begin
		                gotoxy(23,5);
										writeln('Quanto tempo demora a luz solar a chegar');
										gotoxy(38,6);
										write('à Terra?');
										gotoxy(21,10);
										writeln('A- 1 SEGUNDO');
										gotoxy(44,10);
										writeln('B- 1 MINUTO');
										gotoxy(21,13);
										writeln('C- 1 HORA');
										gotoxy(44,13);
										writeln('D- 8 MINUTOS');
										gotoxy(42,17);
										readln(r);
										if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								29:Begin
		                gotoxy(21,5);
										writeln('Qual destes não foi uma colónia de Portugal?');
										gotoxy(21,10);
										writeln('A- ANGOLA');
										gotoxy(44,10);
										writeln('B- MOÇAMBIQUE');
										gotoxy(21,13);
										writeln('C- UGANDA');
										gotoxy(44,13);
										writeln('D- CABO VERDE');
										gotoxy(42,17);
										readln(r);
										if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								30:Begin
		                gotoxy(26,5);
										writeln('Qual é a solução desta equação:');
										gotoxy(37,6);
										write('2(x+4)+6=8');
										gotoxy(21,10);
										writeln('A- 2');
										gotoxy(44,10);
										writeln('B- -3');
										gotoxy(21,13);
										writeln('C- 1');
										gotoxy(44,13);
										writeln('D- -1');
										gotoxy(42,17);
										readln(r);
										if (r = 'B') or (r= 'b') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								31:Begin
		                gotoxy(23,5);
										writeln('Que nome se dá às gónadas masculinas?');
										gotoxy(21,10);
										writeln('A- PRÓSTATA');
										gotoxy(44,10);
										writeln('B- TESTÍCULOS');
										gotoxy(21,13);
										writeln('C- EPIDÍDIMOS');
										gotoxy(44,13);
										writeln('D- PÉNIS');
										gotoxy(42,17);
										readln(r);
										if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								32:Begin
		                gotoxy(23,5);
										writeln('Em que ano Napoleão se tornou imperador?');
										gotoxy(21,10);
										writeln('A- 1801');
										gotoxy(44,10);
										writeln('B- 1804');
										gotoxy(21,13);
										writeln('C- 1704');
										gotoxy(44,13);
										writeln('D- 1701');
										gotoxy(42,17);
										readln(r);
										if (r = 'B') or (r= 'b') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								33:Begin
		                gotoxy(21,5);
										writeln('Quem foi eleito Presidente dos EUA em 2020?');
										gotoxy(21,10);
										writeln('A- DONALD TRUMP');
										gotoxy(44,10);
										writeln('B- JONATHAN BIDEN');
										gotoxy(21,13);
										writeln('C- BERNIE SANDERS');
										gotoxy(44,13);
										writeln('D- JOE BIDEN');
										gotoxy(42,17);
										readln(r);
										if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								34:Begin
		                gotoxy(25,5);
										writeln('Onde se desenvolve um embrião humano?');
										gotoxy(21,10);
										writeln('A- TROMPAS DE');
										gotoxy(21,11);
										write('FALÓPIO');
										gotoxy(44,10);
										writeln('B- VAGINA');
										gotoxy(21,13);
										writeln('C- OVÁRIO');
										gotoxy(44,13);
										writeln('D- ÚTERO');
										gotoxy(42,17);
										readln(r);
										if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								35:Begin
		                gotoxy(23,5);
										writeln('Onde fica situada o museu de Louvre?');
										gotoxy(21,10);
										writeln('A- PARIS');
										gotoxy(44,10);
										writeln('B- ROMA');
										gotoxy(21,13);
										writeln('C- LISBOA');
										gotoxy(44,13);
										writeln('D- MADRID');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								36:Begin
		                gotoxy(25,5);
										writeln('Como se chama o hino de Portugal?');
										gotoxy(21,10);
										writeln('A- HERÓIS DO MAR');
										gotoxy(44,10);
										writeln('B- NOBRE POVO');
										gotoxy(21,13);
										writeln('C- NAÇÃO VALENTE');
										gotoxy(44,13);
										writeln('D- A PORTUGUESA');
										gotoxy(42,17);
										readln(r);
										if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								37:Begin
		                gotoxy(20,5);
										writeln('Qual é o primeiro elemento da tabela periódica');
										gotoxy(21,10);
										writeln('A- OXIGÉNIO');
										gotoxy(44,10);
										writeln('B- HIDROGÉNIO');
										gotoxy(21,13);
										writeln('C- COBRE');
										gotoxy(44,13);
										writeln('D- OURO');
										gotoxy(42,17);
										readln(r);
										if (r = 'B') or (r= 'b') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								38:Begin
		                gotoxy(25,5);
										writeln('Quem escreveu "Os Lusíadas"?');
										gotoxy(21,10);
										writeln('A- GIL VICENTE');
										gotoxy(44,10);
										writeln('B- JOSÉ SARAMAGO');
										gotoxy(21,13);
										writeln('C- CAMÕES');
										gotoxy(44,13);
										writeln('D- FERNANDO PESSOA');
										gotoxy(42,17);
										readln(r);
										if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								39:Begin
		                gotoxy(25,5);
										writeln('Qual dos seguintes não é uma das');
										gotoxy(29,6);
										write('7 maravilhas do mundo?');
										gotoxy(21,10);
										writeln('A- COLOSSO DE RODES');
										gotoxy(44,10);
										writeln('B- ESTÁTUA DE ZEUS');
										gotoxy(21,13);
										writeln('C- TORRE EIFFEIL');
										gotoxy(44,13);
										writeln('D- TEMPLO DE ARTEMIS');
										gotoxy(42,17);
										readln(r);
										if (r = 'c') or (r= 'C') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								40:Begin
		                gotoxy(23,5);
										writeln('Qual é a moeda utilizada na Inglaterra?');
										gotoxy(21,10);
										writeln('A- EURO');
										gotoxy(44,10);
										writeln('B- DÓLAR');
										gotoxy(21,13);
										writeln('C- LIBRA');
										gotoxy(44,13);
										writeln('D- FRANCO');
										gotoxy(42,17);
										readln(r);
										if (r = 'c') or (r= 'C') then pontos[k]:=pontos[k]+1;
										delay(1000);
								   end;
								41:Begin
		                gotoxy(24,5);
										writeln('Qual é a molécula da água?');
										gotoxy(21,10);
										writeln('A- H2O');
										gotoxy(44,10);
										writeln('B- 2H0');
										gotoxy(21,13);
										writeln('C- HO2');
										gotoxy(44,13);
										writeln('D- O2H');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
									 end;
								42:Begin
		                gotoxy(27,5);
										writeln('Quem pintou a Mona Lisa?');
										gotoxy(21,10);
										writeln('A- DA VINCI');
										gotoxy(44,10);
										writeln('B- DONATELLO');
										gotoxy(21,13);
										writeln('C- DICAPRIO');
										gotoxy(44,13);
										writeln('D- MICHELANGELO');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
									 end;
								43:Begin
		                gotoxy(22,5);
										writeln('Qual é o componente principal do ar?');
										gotoxy(21,10);
										writeln('A- OXIGÉNIO');
										gotoxy(44,10);
										writeln('B- AZOTO');
										gotoxy(21,13);
										writeln('C- VAPOR DE ÁGUA');
										gotoxy(44,13);
										writeln('D- ÁRGON');
										gotoxy(42,17);
										readln(r);
										if (r = 'B') or (r= 'b') then pontos[k]:=pontos[k]+1;
										delay(1000);
									 end;
								44:Begin
		                gotoxy(22,5);
										writeln('A ciência que estuda a Terra é...');
										gotoxy(21,10);
										writeln('A- BIOLOGIA');
										gotoxy(44,10);
										writeln('B- FÍSICA');
										gotoxy(21,13);
										writeln('C- VULCANOLOGIA');
										gotoxy(44,13);
										writeln('D- GEOLOGIA');
										gotoxy(42,17);
										readln(r);
										if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
										delay(1000);
									 end;
								45:Begin
		                gotoxy(22,5);
										writeln('São exemplos de rochas sedimentares...');
										gotoxy(21,10);
										writeln('A- BASALTO');
										gotoxy(44,10);
										writeln('B- AREIA');
										gotoxy(21,13);
										writeln('C- GRANITO');
										gotoxy(44,13);
										writeln('D- MÁRMORE');
										gotoxy(42,17);
										readln(r);
										if (r = 'B') or (r= 'b') then pontos[k]:=pontos[k]+1;
										delay(1000);
									 end;
								46:Begin
		                gotoxy(23,5);
										writeln('A ciência que estuda sismos é a...?');
										gotoxy(21,10);
										writeln('A- SISMOGRAFIA');
										gotoxy(44,10);
										writeln('B- GEOGRAFIA');
										gotoxy(21,13);
										writeln('C- ASTRONOMIA');
										gotoxy(44,13);
										writeln('D- SISMOLOGIA');
										gotoxy(42,17);
										readln(r);
										if (r = 'D') or (r= 'd') then pontos[k]:=pontos[k]+1;
										delay(1000);
									 end;
								47:Begin
		                gotoxy(26,5);
										writeln('Qual destes é mamífero?');
										gotoxy(21,10);
										writeln('A- SAPO');
										gotoxy(44,10);
										writeln('B- COBRA');
										gotoxy(21,13);
										writeln('C- MORCEGO');
										gotoxy(44,13);
										writeln('D- ARANHA');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
									 end;
								48:Begin
		                gotoxy(22,5);
										writeln('Qual é o livro mais vendido de sempre?');
										gotoxy(21,10);
										writeln('A- O SENHOR DOS ANÉIS');
										gotoxy(44,10);
										writeln('B- HARRY POTTER');
										gotoxy(21,13);
										writeln('C- BÍBLIA');
										gotoxy(44,13);
										writeln('D- O HOBBIT');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
									 end;	
								49:Begin
		                gotoxy(23,5);
										writeln('Quem foi o primeiro homem na lua?');
										gotoxy(21,10);
										writeln('A- KANYE WEST');
										gotoxy(44,10);
										writeln('B- NEIL ARMSTRONG');
										gotoxy(21,13);
										writeln('C- ISAAC NEWTON');
										gotoxy(44,13);
										writeln('D- ALBERT EINSTEIN');
										gotoxy(42,17);
										readln(r);
										if (r = 'A') or (r= 'a') then pontos[k]:=pontos[k]+1;
										delay(1000);
									 end;
								50:Begin
		                gotoxy(24,5);
										writeln('Qual dos seguintes é omnívoro?');
										gotoxy(21,10);
										writeln('A- GIRAFA');
										gotoxy(44,10);
										writeln('B- HIENA');
										gotoxy(21,13);
										writeln('C- SER HUMANO');
										gotoxy(44,13);
										writeln('D- LOBO');
										gotoxy(42,17);
										readln(r);
										if (r = 'C') or (r= 'c') then pontos[k]:=pontos[k]+1;
										delay(1000);
									 end; 	 					 	  
				    end;
				    clrscr;
				    f:=f+1;
				  	until f=6;
				  	limiteperguntas[k]:=limiteperguntas[k]+1;
				end;
      3:Begin
				 gotoxy(40,5);
				 textcolor(magenta);
				 writeln('L E A D E R B O A R D');
				 for i:=30 to 70 do
				 	begin
				 	 gotoxy(i,6);
				 	 write(#205);
				 	 gotoxy(i,20);
				 	 write(#205);
				 	end;
				 for i:=7 to 19 do
				 	begin
				 		gotoxy(29,i);
				 		write(#186);
				 		gotoxy(71,i);
				 		write(#186);
					end;					
				gotoxy(29,6);
		    write(#201);
		    gotoxy(71,6);
		    write(#187);
		    gotoxy(29,20);
		    write(#200);
		    gotoxy(71,20);
		    write(#188);	 
      	 	for i:=1 to k do
      	 		begin
      	 			textcolor(yellow);
      	 			gotoxy(33,i+6);
         			writeln(nome[i]);
         			gotoxy(65,i+6);
         			writeln(pontos[i],'/',6*limiteperguntas[i]);				                               
				 		end;
					gotoxy(37,21);
					writeln('Pressione <Enter> para sair');                        
				end;
    end;
    readln;
    clrscr;
  until op=4;  
End.